[tool]
[tool.poetry]
authors = ["Your Name <you@example.com>"]
name = "root"
version = "0.0.0"
[tool.poetry.dependencies]
"discord.py" = "*"
flask = "*"
python = "^3.7"
replit = "*"
fuzzywuzzy = "^0.18.0"
pandas = "^1.0"
pykakasi = "^1.2"
bs4 = "^0.0.1"
lxml = "^4.5"
