[tool]
[tool.poetry]
authors = ["Your Name <you@example.com>"]
name = "root"
version = "0.0.0"
description = "00"
[tool.poetry.dependencies]
bs4 = "^0.0.1"
"discord.py" = "*"
flask = "*"
fuzzywuzzy = "^0.18.0"
lxml = "^4.5"
pandas = "^1.0"
pykakasi = "^1.2"
python = "^3.8"
replit = "*"
