paff=[ ' [PAFF] Body Talk ', ' [PAFF] Survive ', ' [PAFF] Bullet Waiting for Me (James Landino remix) ', ' [PAFF] KANATA ', ' [PAFF] Fight Another Day (Andy Tunstall remix) ', ' [PAFF] Baptism of Fire (CliqTrack remix) ', ' [PAFF] Fireflies (Funk Fiction remix) ', ' [PAFF] Gravity ', ' [PAFF] Re:Boost ', ' [PAFF] Green Hope ', ' [PAFF] Under the same sky ', ' [PAFF] So In Love ', ' [PAFF] Winter Games ', ' [PAFF] New World ', ' [PAFF] SECRETWEAPON ', ' [PAFF] Lilac for Anabel ', ' [PAFF] Who Am I? ', ' [PAFF] More Than Diamond ', ' [PAFF] Blossoms for Life ', ' [PAFF] Cityscape ', ' [PAFF] Favorites ', ' [PAFF] Make Me Alive ', ' [PAFF] Light up my love!! ', ' [PAFF] Super attractor ', ' [PAFF] Recall ', ' [PAFF] I Wish You Were Mine ', ' [PAFF] PIXIE DUST ', ' [PAFF] Gravity (GLITCH) ', ' [PAFF] KANATA (GLITCH) ',' [PAFF] Sleeping Beast ', ' [PAFF] Re:Boost (GLITCH) ', ' [PAFF] Inspiration ', ' [PAFF] No-Effected World ' ]

nekow=[ ' [NEKO#ΦωΦ] The Spark ', ' [NEKO#ΦωΦ] Resurrection 💚 ', ' [NEKO#ΦωΦ] One Way Love ', ' [NEKO#ΦωΦ] Happiness Breeze ', ' [NEKO#ΦωΦ] Alterna Pt.1 -Cosmogony- ', ' [NEKO#ΦωΦ] Zealous Hearts (Rayark Edit) ', ' [NEKO#ΦωΦ] Keep it up ', ' [NEKO#ΦωΦ] CODE NAME : GAMMA ', ' [NEKO#ΦωΦ] Blow my mind ', ' [NEKO#ΦωΦ] Chrome VOX ', ' [NEKO#ΦωΦ] Hard Landing ', ' [NEKO#ΦωΦ] Brain Power ', ' [NEKO#ΦωΦ] Sdorica The Story Unfolds ', ' [NEKO#ΦωΦ] Hesitant Blade ', ' [NEKO#ΦωΦ] PrayStation (HiTECH NINJA Remix) ', ' [NEKO#ΦωΦ] 100sec Cat Dreams ', ' [NEKO#ΦωΦ] REmorse ', ' [NEKO#ΦωΦ] Stranger ', ' [NEKO#ΦωΦ] 小悪魔×3の大脫走！？ ', ' [NEKO#ΦωΦ] extinguisher ', ' [NEKO#ΦωΦ] Online ', ' [NEKO#ΦωΦ] Sunday Night Blues ', ' [NEKO#ΦωΦ] FUJIN Rumble ', ' [NEKO#ΦωΦ] For You the Bellz Toll ', ' [NEKO#ΦωΦ] Blow My Mind (tpz Overheat Remix) ', ' [NEKO#ΦωΦ] Maboroshi ', ' [NEKO#ΦωΦ] TOKONOMA Spacewalk ', ' [NEKO#ΦωΦ] UnNOT!CED ', ' [NEKO#ΦωΦ] 下水鳴動して鼠一匹 ', ' [NEKO#ΦωΦ] Capybara Kids` Paradise ', ' [NEKO#ΦωΦ] Walnuts Walkers ', ' [NEKO#ΦωΦ] Hydra ', ' [NEKO#ΦωΦ] Liberation ', ' [NEKO#ΦωΦ] Ramen is God ', ' [NEKO#ΦωΦ] Re: VeLΔTiØN ~ 光道ト破壊ノ双白翼~ ', ' [NEKO#ΦωΦ] Rebirth ', ' [NEKO#ΦωΦ] Hydra (GLITCH) ', ' [NEKO#ΦωΦ] Liberation (GLITCH) 🔥 ', ' [NEKO#ΦωΦ] Ramen is God (GLITCH) 🔥 ', ' [NEKO#ΦωΦ] Re: VeLΔTiØN ~ 光道ト破壊ノ双白翼~ (GLITCH) 🔥 ', ' [NEKO#ΦωΦ] Rebirth (GLITCH) ', ' [NEKO#ΦωΦ] Rei ', ' [NEKO#ΦωΦ] Chrome VOX (GLITCH) ', ' [NEKO#ΦωΦ] Happiness Breeze (GLITCH) ', ' [NEKO#ΦωΦ] 警け！ ', ' [NEKO#ΦωΦ] 気楽なCloudy ', ' [NEKO#ΦωΦ] DON`T STOP ROCKIN` ', ' [NEKO#ΦωΦ] 超常マイマイン ', ' [NEKO#ΦωΦ] Oshama Scramble! ', ' [NEKO#ΦωΦ] Glorious Crown ', ' [NEKO#ΦωΦ] Caliburne ～Story of the Legendary sword～ ', ' [NEKO#ΦωΦ] Play the Future ', ' [NEKO#ΦωΦ] Ask to Wind Live Mix ', ' [NEKO#ΦωΦ] Hello Pinky ', ' [NEKO#ΦωΦ] U.A.D ', ' [NEKO#ΦωΦ] glory day ', ' [NEKO#ΦωΦ] BlythE ', ' [NEKO#ΦωΦ] We`re All Gonna Die ', ' [NEKO#ΦωΦ] End of the Moonlight ', ' [NEKO#ΦωΦ] Nightmare ', ' [NEKO#ΦωΦ] OblivioN ', ' [NEKO#ΦωΦ] LOUDER MACHINE ', ' [NEKO#ΦωΦ] Pounding Destination ', ' [NEKO#ΦωΦ] Stewrica -Cross- ' ]

robohead=[ ' [ROBO_Head] Deadly Slot Game ', ' [ROBO_Head] Make Me Burn ', ' [ROBO_Head] Restriction ', ' [ROBO_Head] Luolimasi ', ' [ROBO_Head] Claim the Game ', ' [ROBO_Head] Devillic Sphere ', ' [ROBO_Head] Pure Powerstomper ', ' [ROBO_Head] Celestial Sounds (KIVΛ Remix) ', ' [ROBO_Head] Grimoire of Crimson ', ' [ROBO_Head] Dasein ', ' [ROBO_Head] CHAOS ', ' [ROBO_Head] EMber ', ' [ROBO_Head] Midnight ', ' [ROBO_Head] Sickest City ', ' [ROBO_Head] Jazzy Glitch Machine ', ' [ROBO_Head] dimensionalize nervous breakdown (rev.flat) ', ' [ROBO_Head] cold ', ' [ROBO_Head] NRG_Tech ', ' [ROBO_Head] Break Through the Barrier ', ' [ROBO_Head] Dead Master ', ' [ROBO_Head] Dead Point ', ' [ROBO_Head] Nocturnal Type ', ' [ROBO_Head] Accelerator ', ' [ROBO_Head] Armaros ', ' [ROBO_Head] Break the Core ', ' [ROBO_Head] Milky Way Galaxy (SIHanatsuka Remix) ', ' [ROBO_Head] ViRUS ', ' [ROBO_Head] Awakening ', ' [ROBO_Head] Hagiasmos ', ' [ROBO_Head] Fade Into The Darkness ', ' [ROBO_Head] SHIRO ', ' [ROBO_Head] Tunnef`s Nightmare ', ' [ROBO_Head] Dasein (GLITCH) ', ' [ROBO_Head] Deadly Slot Game (GLITCH) ' ]

ivy=[ ' [Ivy] Reset ', ' [Ivy] D R G ', ' [Ivy] Sentimental Journey ', ' [Ivy] Biotonic ', ' [Ivy] Alexandrite ', ' [Ivy] Tokiwatari ', ' [Ivy] Purge ', ' [Ivy] Area184 ', ' [Ivy] BloodyMare ', ' [Ivy] AssaultMare ', ' [Ivy] Lunar Mare ', ' [Ivy] 99 Glooms ', ' [Ivy] Pressure ', ' [Ivy] V. ', ' [Ivy] Cristalisia ', ' [Ivy] Occidens ', ' [Ivy] Red Five ', ' [Ivy] Homebound Train & Moving Thoughts ', ' [Ivy] iL 🔥 ', ' [Ivy] CODE NAME : SIGMA ', ' [Ivy] New Challenger Approaching ', ' [Ivy] What`s Your PR.Ice? ', ' [Ivy] VIS::CRACKED ', ' [Ivy] Wicked Ceremony ',' [Ivy] Bloody Purity ',' [Ivy] Masquerade ',' [Ivy] Quantum Labyrinth ',' [Ivy] Saika ',' [Ivy] To Further Dream ', ' [Ivy] DigiGroove ', ' [Ivy] Heat Ring ', ' [Ivy] Leaving All Behind ', ' [Ivy] Symmetry ', ' [Ivy] Time to Fight ', ' [Ivy] Libera me ', ' [Ivy] Qualia ', ' [Ivy] Summer Zephyr ', ' [Ivy] Sovereign ', ' [Ivy] FREEDOM DiVE', ' [Ivy] Conflict ', ' [Ivy] Conflict (GLITCH) ', ' [Ivy] paradigm-paragramme-program ', ' [Ivy] Secret Garden ', ' [Ivy] Halcyon ' ]

cp=[ ' [Crystal PuNK] Effervesce ', ' [Crystal PuNK] Chandelier XIII ', ' [Crystal PuNK] Sunshine Duration ', ' [Crystal PuNK] Deep Dive ', ' [Crystal PuNK] βinαrΨ ', ' [Crystal PuNK] Dark Madness ', ' [Crystal PuNK] Darling Staring... ', ' [Crystal PuNK] Crimson Fate ', ' [Crystal PuNK] Familiar Craze ', ' [Crystal PuNK] Malstream ', ' [Crystal PuNK] V.R.W (feat. shully) ', ' [Crystal PuNK] velkinta feat. Cikado & A-Tse ',' [Crystal PuNK] The Cross (feat. Silvia Su) ' ]

vanessa=[ ' [Vanessa] Anchor ', ' [Vanessa] syūten ', ' [Vanessa] Rosa Rubus ', ' [Vanessa] XYZ ', ' [Vanessa] II-V ', ' [Vanessa] Chaos and Abyss -3rd Movement- ', ' [Vanessa] duality ', ' [Vanessa] RA ', ' [Vanessa] CHAOS //System Offline// ', ' [Vanessa] V. //System Offline// ', ' [Vanessa]  ͟͞͝ ||̛  ', ' [Vanessa] Used to be ', ' [Vanessa] The whole rest ' ]

bobo=[ ' [Bo Bo] Äventyr ', ' [Bo Bo] NORDLYS ', ' [Bo Bo] Snow Blossom ', ' [Bo Bo] Quinsialyn ', ' [Bo Bo] 黎明-REIMEI- ', ' [Bo Bo] End of fireworks ', ' [Bo Bo] 神様と羊飼い ' ]

miku=[ ' [Miku] Blue Star ', ' [Miku] BREAK IT ', ' [Miku] Can`t Make a Song!! ', ' [Miku] Miku ', ' [Miku] Sharing The World ', ' [Miku] Venus di Ujung Jari ', ' [Miku] ラッキー☆オーブ ', ' [Miku] 魔法みたいなミュージック！ ', ' [Miku] 月西江 ', ' [Miku] Ten Thousand Stars ', ' [Miku] Glass Wall ', ' [Miku] Cybernetic ', ' [Miku] Decade ', ' [Miku] ラッキー☆オーブ (3R2 Remix) ' ]

ai= [ ' [Kizuna AI] new world (Prod. Yunomi)', ' [Kizuna AI] miracle step (Prod. Nor) ', ' [Kizuna AI] AIAIAI (feat. 中田ヤスタカ) ', ' [Kizuna AI] future base (Prod. Yunomi) ', ' [Kizuna AI] meet you (Prod. DÉ DÉ MOUSE) ', ' [Kizuna AI] Hello, Morning (Prod. Nor) ', ' [Kizuna AI] over the reality (Prod. Avec Avec) ', ' [Kizuna AI] melty world (Prod. TeddyLoid) ', ' [Kizuna AI] mirai (Prod. ☆Taku Takahashi) ', ' [Kizuna AI] hello, alone (Prod. MATZ) ' ]

alice= [ ' [Alice] Friction ', ' [Alice] Legacy ', ' [Alice] Living In The One ', ' [Alice] YUBIKIRI-GENMAN ', ' [Alice] I hate to tell you ', ' [Alice] Utopiosphere ', ' [Alice] Marigold ', ' [Alice] The Beautiful Moonlight ', ' [Alice] 都市の呼吸 ', ' [Alice] To next page ' ]

xenon=[ ' [Xenon] INSPION ', ' [Xenon] Whispers in my Head ', ' [Xenon] Return ', ' [Xenon] concentric circles ', ' [Xenon] Fighting ', ' [Xenon] To The Light ', ' [Xenon] Phantom Razor ', ' [Xenon] Black Hole ', ' [Xenon] SAMURAI ', ' [Xenon] IOLITE-SUNSTONE ', ' [Xenon] Sairai ', ' [Xenon] Ultimate feat. 放課後のあいつ ', ' [Xenon] Karma ', ' [Xenon] Chosen ', ' [Xenon] Violet ', ' [Xenon] Asylum ', ' [Xenon] Phantom Razor (GLITCH) ' ]

conner=[' [ConneR] Xiorc ', ' [ConneR] REBELLIUM ', ' [ConneR] Imprinting ', ' [ConneR] Gekkouka ', ' [ConneR] Light of Buenos Aires ', ' [ConneR] tondari-hanetari ', ' [ConneR] Abduction ', ' [ConneR] Nostalgia Sonatina ', ' [ConneR] I luv U ', ' [ConneR] Instinct ', ' [ConneR] Floor of Lava 🔥 ', ' [ConneR] Aphasia ', ' [ConneR] Olympia ', ' [ConneR] Demetrius ', ' [ConneR] L`Ultima Cena ', ' [ConneR] Deus Ex Machina ', ' [ConneR] Fur War, Pur War ', ' [ConneR] Imprinting (GLITCH) ' ]

cherry=[ ' [Cherry] Scenery in your eyes ', ' [Cherry] LEVEL4 ', ' [Cherry] Living for you (Andy Tunstall remix) ', ' [Cherry] I`M NOT ', ' [Cherry] Stop at nothing (Andy Tunstall remix) ', ' [Cherry] RETRIEVE ', ' [Cherry] Still ', ' [Cherry] CREDENCE ', ' [Cherry] SYSTEMFEIT ', ' [Cherry] hunted ', ' [Cherry] Capture me ', ' [Cherry] Realize ', ' [Cherry] CREDENCE (GLITCH) ' ]

joe=[ ' [Joe] Childish ', ' [Joe] Turnstile Jumper ', ' [Joe] Juicy Gossip ', ' [Joe] Standby for Action ', ' [Joe] Open the Game ', ' [Joe] Hydrangea ', ' [Joe] Absolutely ', ' [Joe] Higher and Higher ', ' [Joe] Take me to the Future ', ' [Joe] Nautilus ', ' [Joe] Bass Music ', ' [Joe] Hydrangea (GLITCH) ' ]

sagar=[ ' [Sagar] Amenemhat ', ' [Sagar] Elysium ', ' [Sagar] Immram Brain ', ' [Sagar] Space Alien ', ' [Sagar] Doldrums ', ' [Sagar] Nídhögg ', ' [Sagar] Legacy ', ' [Sagar] A Portent of the Silver Wheel ', ' [Sagar] Sacrifice ', ' [Sagar] Return of the Lamp ' ]

rin=[' [Rin] The Siege ', ' [Rin] The Grand Debate ', ' [Rin] 三灯火 ', ' [Rin] 「妖怪録、我し来にけり。」 ', ' [Rin] Starry Summoner ', ' [Rin] すゝめ☆クノイチの巻 ', ' [Rin] 彩 ', ' [Rin] 決戦 ', ' [Rin] Mari-Temari ', ' [Rin] Inari ' ]


aroma=[ ' [Aroma] change ', ' [Aroma] No One Can`t Stop Me ', ' [Aroma] Spotlight On ', ' [Aroma] Bring the light ', ' [Aroma] Make U Mine ', ' [Aroma] Anzen Na Kusuri ', ' [Aroma] 漂流 ', ' [Aroma] Perspectives ', ' [Aroma] 風の声 ', ' [Aroma] Neon Escape ', ' [Aroma] Beautiful Lie ', ' [Aroma] Perspectives (GLITCH) ' ]

nora=[ ' [Nora] Accelerator ', ' [Nora] Dance till Dawn ', ' [Nora] Uranus ', ' [Nora] Drop the World ', ' [Nora] Starlight (KIVΛ Remix) ', ' [Nora] Bastard of Hardcore ', ' [Nora] Jakarta PROGRESSION ', ' [Nora] Eternity ', ' [Nora] Phagy Mutation ', ' [Nora] ATONEMENT ', ' [Nora] Grand Emotion ' ]

neko=[ ' [Neko] Chocolate Missile ', ' [Neko] I can avoid it.#φωφ ', ' [Neko] Pink Graduation ', ' [Neko] 一啖兩啖 ', ' [Neko] Mammal ', ' [Neko] Blah!! ', ' [Neko] リラ ', ' [Neko] Log In ', ' [Neko] DJ Mashiro is dead or alive ', ' [Neko] Re:incRnaTiØN ～夕焼ケ世界ノ決別ヲ～ 🔥 ', ' [Neko] R.I.P. ' ]


free = [ ' [PAFF] KANATA ', ' [PAFF] Under the same sky ', ' [PAFF] Winter Games ', ' [PAFF] More Than Diamond ', ' [PAFF] Recall ', ' [NEKO#ΦωΦ] One Way Love ', ' [PAFF] Survive ', ' [PAFF] Fight Another Day (Andy Tunstall remix) ', ' [PAFF] Fireflies (Funk Fiction remix) ', ' [PAFF] New World ', ' [PAFF] Who Am I? ', ' [NEKO#ΦωΦ] Hard Landing ', ' [NEKO#ΦωΦ] Sdorica The Story Unfolds ', ' [PAFF] Bullet Waiting for Me (James Landino remix) ', ' [PAFF] Re:Boost ', ' [PAFF] Green Hope ', ' [PAFF] Blossoms for Life ', ' [NEKO#ΦωΦ] Hesitant Blade ', ' [NEKO#ΦωΦ] extinguisher ', ' [NEKO#ΦωΦ] Rei ', ' [ROBO_Head] Restriction ', ' [ROBO_Head] Luolimasi ', ' [ROBO_Head] Grimoire of Crimson ', ' [ROBO_Head] Nocturnal Type ', ' [Ivy] D R G ', ' [Crystal PuNK] The Cross (feat. Silvia Su) ', ' [PAFF] Body Talk ', ' [PAFF] Baptism of Fire (CliqTrack remix) ', ' [PAFF] Gravity ', ' [NEKO#ΦωΦ] The Spark ', ' [NEKO#ΦωΦ] Resurrection 💚 ', ' [NEKO#ΦωΦ] Happiness Breeze ', ' [NEKO#ΦωΦ] Alterna Pt.1 -Cosmogony- ', ' [NEKO#ΦωΦ] Zealous Hearts (Rayark Edit) ', ' [ROBO_Head] Deadly Slot Game ', ' [ROBO_Head] Make Me Burn ', ' [ROBO_Head] Claim the Game ', ' [ROBO_Head] Dasein ', ' [Ivy] Reset ', ' [Ivy] Purge ', ' [Ivy] Area184 ', ' [Ivy] Pressure ', ' [Crystal PuNK] Chandelier XIII ', ' [Crystal PuNK] Sunshine Duration ', ' [Crystal PuNK] βinαrΨ ', ' [PAFF] Lilac for Anabel ', ' [NEKO#ΦωΦ] Brain Power ', ' [ROBO_Head] Devillic Sphere ', ' [ROBO_Head] Pure Powerstomper ', ' [ROBO_Head] EMber ', ' [ROBO_Head] Midnight ', ' [ROBO_Head] Dead Point ', ' [Ivy] Biotonic ', ' [Ivy] Alexandrite ', ' [Ivy] Tokiwatari ', ' [Ivy] BloodyMare ', ' [Crystal PuNK] Effervesce ', ' [Crystal PuNK] Deep Dive ', ' [Crystal PuNK] Dark Madness ', ' [PAFF] SECRET;WEAPON ', ' [NEKO#ΦωΦ] Keep it up ', ' [NEKO#ΦωΦ] Blow my mind ', ' [NEKO#ΦωΦ] For You the Bellz Toll ', ' [ROBO_Head] Celestial Sounds (KIVΛ Remix) ', ' [ROBO_Head] CHAOS ', ' [Ivy] Sentimental Journey ', ' [Ivy] AssaultMare ', ' [Ivy] Lunar Mare ', ' [Ivy] 99 Glooms ', ' [NEKO#ΦωΦ] CODE NAME : GAMMA ', ' [NEKO#ΦωΦ] Chrome VOX ', ' [NEKO#ΦωΦ] FUJIN Rumble ', ' [Ivy] V. ', ' [Vanessa] Anchor ', ' [Vanessa] syūten ', ' [Vanessa] Rosa Rubus ', ' [Vanessa] XYZ ', ' [Vanessa] II-V ', ' [Vanessa] Chaos and Abyss -3rd Movement- ', ' [Vanessa] duality ', ' [Vanessa] RA ', ' [Vanessa] CHAOS //System Offline// ', ' [Vanessa] V. //System Offline// ', ' [Vanessa]  ͟͞͝ ||̛  ', ' [Vanessa] Used to be ', ' [Vanessa] The whole rest ', ' [Ivy] Summer Zephyr ', ' [Ivy] Sovereign ', ' [Ivy] paradigm-paragramme-program ', ' [Ivy] Secret Garden ', ' [NEKO#ΦωΦ] Pounding Destination ', ' [NEKO#ΦωΦ] Stewrica -Cross- ', ' [Bo Bo] Äventyr ', ' [Bo Bo] NORDLYS ', ' [Bo Bo] Snow Blossom ', ' [Bo Bo] Quinsialyn ', ' [Bo Bo] 黎明-REIMEI- ' ]

capso = [ ' [Ivy] Bloody Purity ',' [Ivy] Masquerade ',' [Ivy] Quantum Labyrinth ',' [Ivy] Saika ',' [Ivy] To Further Dream ', ' [PAFF] Gravity (GLITCH) ', ' [NEKO#ΦωΦ] Chrome VOX (GLITCH) ', ' [ROBO_Head] Dasein (GLITCH) ', ' [Xenon] Phantom Razor (GLITCH) ', ' [ConneR] Imprinting (GLITCH) ', ' [Ivy] Libera me ', ' [Ivy] Qualia ', ' [PAFF] KANATA (GLITCH) ', ' [NEKO#ΦωΦ] Happiness Breeze (GLITCH) ', ' [ROBO_Head] Deadly Slot Game (GLITCH) ', ' [Cherry] CREDENCE (GLITCH) ', ' [Ivy] FREEDOM DiVE', ' [Ivy] Conflict (GLITCH) ', ' [Joe] Hydrangea (GLITCH) ', ' [PAFF] Re:Boost (GLITCH) ', ' [Aroma] Perspectives (GLITCH) ', ' [Ivy] Halcyon ' ]

bm = [ ' [PAFF] So In Love ', ' [PAFF] Cityscape ', ' [PAFF] Favorites ', ' [PAFF] Make Me Alive ', ' [PAFF] Light up my love!! ', ' [PAFF] Super attractor ', ' [PAFF] I Wish You Were Mine ', ' [PAFF] PIXIE DUST ', ' [NEKO#ΦωΦ] PrayStation (HiTECH NINJA Remix) ', ' [NEKO#ΦωΦ] 100sec Cat Dreams ', ' [NEKO#ΦωΦ] REmorse ', ' [NEKO#ΦωΦ] Stranger ', ' [NEKO#ΦωΦ] 小悪魔×3の大脫走！？ ', ' [NEKO#ΦωΦ] Online ', ' [NEKO#ΦωΦ] Sunday Night Blues ', ' [NEKO#ΦωΦ] Blow My Mind (tpz Overheat Remix) ', ' [NEKO#ΦωΦ] Maboroshi ', ' [NEKO#ΦωΦ] TOKONOMA Spacewalk ', ' [NEKO#ΦωΦ] UnNOT!CED ', ' [NEKO#ΦωΦ] 下水鳴動して鼠一匹 ', ' [NEKO#ΦωΦ] Capybara Kids` Paradise ', ' [NEKO#ΦωΦ] Walnuts Walkers ', ' [ROBO_Head] Sickest City ', ' [ROBO_Head] Jazzy Glitch Machine ', ' [ROBO_Head] dimensionalize nervous breakdown (rev.flat) ', ' [ROBO_Head] cold ', ' [ROBO_Head] NRG_Tech ', ' [ROBO_Head] Break Through the Barrier ', ' [ROBO_Head] Dead Master ', ' [ROBO_Head] Accelerator ', ' [ROBO_Head] Armaros ', ' [ROBO_Head] Break the Core ', ' [ROBO_Head] Milky Way Galaxy (SIHanatsuka Remix) ', ' [ROBO_Head] ViRUS ', ' [ROBO_Head] Awakening ', ' [ROBO_Head] Hagiasmos ', ' [ROBO_Head] Fade Into The Darkness ', ' [ROBO_Head] SHIRO ', ' [ROBO_Head] Tunnef`s Nightmare ', ' [Ivy] Cristalisia ', ' [Ivy] Occidens ', ' [Ivy] Red Five ', ' [Ivy] Homebound Train & Moving Thoughts ', ' [Ivy] iL 🔥 ', ' [Ivy] CODE NAME : SIGMA ', ' [Ivy] New Challenger Approaching ', ' [Ivy] What`s Your PR.Ice? ', ' [Ivy] VIS::CRACKED ', ' [Ivy] Wicked Ceremony ', ' [Crystal PuNK] Darling Staring... ', ' [Crystal PuNK] Crimson Fate ', ' [Crystal PuNK] Familiar Craze ', ' [Crystal PuNK] Malstream ', ' [Crystal PuNK] V.R.W (feat. shully) ', ' [Crystal PuNK] velkinta feat. Cikado & A-Tse ', ' [NEKO#ΦωΦ] Hydra ', ' [NEKO#ΦωΦ] Liberation ', ' [NEKO#ΦωΦ] Ramen is God ', ' [NEKO#ΦωΦ] Re: VeLΔTiØN ~ 光道ト破壊ノ双白翼~ ', ' [NEKO#ΦωΦ] Rebirth ', ' [NEKO#ΦωΦ] Hydra (GLITCH) ', ' [NEKO#ΦωΦ] Liberation (GLITCH) 🔥 ', ' [NEKO#ΦωΦ] Ramen is God (GLITCH) 🔥 ', ' [NEKO#ΦωΦ] Re: VeLΔTiØN ~ 光道ト破壊ノ双白翼~ (GLITCH) 🔥 ', ' [NEKO#ΦωΦ] Rebirth (GLITCH) ', ' [Ivy] DigiGroove ', ' [Ivy] Heat Ring ', ' [Ivy] Leaving All Behind ', ' [Ivy] Symmetry ', ' [Ivy] Time to Fight ', ' [NEKO#ΦωΦ] DON`T STOP ROCKIN` ', ' [NEKO#ΦωΦ] 超常マイマイン ', ' [NEKO#ΦωΦ] Oshama Scramble! ', ' [NEKO#ΦωΦ] Glorious Crown ', ' [NEKO#ΦωΦ] Caliburne ～Story of the Legendary sword～ ', ' [NEKO#ΦωΦ] Play the Future ', ' [NEKO#ΦωΦ] Ask to Wind Live Mix ', ' [NEKO#ΦωΦ] Hello Pinky ', ' [NEKO#ΦωΦ] U.A.D ', ' [NEKO#ΦωΦ] glory day ', ' [NEKO#ΦωΦ] BlythE ', ' [NEKO#ΦωΦ] We`re All Gonna Die ', ' [NEKO#ΦωΦ] End of the Moonlight ', ' [NEKO#ΦωΦ] Nightmare ', ' [NEKO#ΦωΦ] OblivioN ', ' [PAFF] Inspiration ', ' [PAFF] No-Effected World ', ' [NEKO#ΦωΦ] LOUDER MACHINE ', ' [Bo Bo] End of fireworks ', ' [Bo Bo] 神様と羊飼い ' ]


glitch = [ ' [NEKO#ΦωΦ] Hydra (GLITCH) ', ' [NEKO#ΦωΦ] Liberation (GLITCH) 🔥 ', ' [NEKO#ΦωΦ] Ramen is God (GLITCH) 🔥 ', ' [NEKO#ΦωΦ] Re: VeLΔTiØN ~ 光道ト破壊ノ双白翼~ (GLITCH) 🔥 ', ' [NEKO#ΦωΦ] Rebirth (GLITCH) ', ' [PAFF] Gravity (GLITCH) ', ' [NEKO#ΦωΦ] Chrome VOX (GLITCH) ', ' [ROBO_Head] Dasein (GLITCH) ', ' [Xenon] Phantom Razor (GLITCH) ', ' [ConneR] Imprinting (GLITCH) ', ' [PAFF] KANATA (GLITCH) ', ' [NEKO#ΦωΦ] Happiness Breeze (GLITCH) ', ' [ROBO_Head] Deadly Slot Game (GLITCH) ', ' [Cherry] CREDENCE (GLITCH) ', ' [PAFF] Re:Boost (GLITCH) ', ' [Joe] Hydrangea (GLITCH) ', ' [Aroma] Perspectives (GLITCH) ', ' [Ivy] Conflict (GLITCH) ' ]

xv = [ ' [NEKO#ΦωΦ] CODE NAME : GAMMA ', ' [NEKO#ΦωΦ] Chrome VOX ', ' [NEKO#ΦωΦ] FUJIN Rumble ', ' [NEKO#ΦωΦ] REmorse ', ' [NEKO#ΦωΦ] Blow My Mind (tpz Overheat Remix) ', ' [NEKO#ΦωΦ] Capybara Kids` Paradise ', ' [Neko] Re:incRnaTiØN ～夕焼ケ世界ノ決別ヲ～ 🔥 ', ' [Ivy] V. ', ' [Ivy] iL 🔥 ', ' [Ivy] CODE NAME : SIGMA ', ' [ConneR] Floor of Lava 🔥 ', ' [ConneR] Fur War, Pur War ', ' [NEKO#ΦωΦ] Hydra (GLITCH) ', ' [NEKO#ΦωΦ] Liberation (GLITCH) 🔥 ', ' [NEKO#ΦωΦ] Ramen is God (GLITCH) 🔥 ', ' [NEKO#ΦωΦ] Re: VeLΔTiØN ~ 光道ト破壊ノ双白翼~ (GLITCH) 🔥 ', ' [NEKO#ΦωΦ] Rebirth (GLITCH) ', ' [NEKO#ΦωΦ] Chrome VOX (GLITCH) ', ' [ConneR] Imprinting (GLITCH) ', ' [Ivy] Symmetry ', ' [Vanessa] XYZ ', ' [Vanessa] Chaos and Abyss -3rd Movement- ', ' [Ivy] FREEDOM DiVE', ' [Ivy] Conflict ', ' [Ivy] Conflict (GLITCH) ', ' [NEKO#ΦωΦ] Nightmare ', ' [NEKO#ΦωΦ] Glorious Crown ', ' [NEKO#ΦωΦ] Caliburne ～Story of the Legendary sword～ ', ' [Alice] Marigold '  ]

xiv = [ ' [PAFF] SECRET;WEAPON ', ' [PAFF] Super attractor ', ' [Aroma] 漂流 ', ' [NEKO#ΦωΦ] Keep it up ', ' [NEKO#ΦωΦ] Blow my mind ', ' [NEKO#ΦωΦ] For You the Bellz Toll ', ' [NEKO#ΦωΦ] 100sec Cat Dreams ', ' [NEKO#ΦωΦ] 小悪魔×3の大脫走！？ ', ' [NEKO#ΦωΦ] Maboroshi ', ' [Neko] Mammal ', ' [Neko] Blah!! ', ' [Neko] DJ Mashiro is dead or alive ', ' [ROBO_Head] Celestial Sounds (KIVΛ Remix) ', ' [ROBO_Head] CHAOS ', ' [ROBO_Head] Sickest City ', ' [ROBO_Head] Break Through the Barrier ', ' [ROBO_Head] Break The Core ', ' [ROBO_Head] Tunnef`s Nightmare ', ' [Nora] Accelerator ', ' [Nora] Drop The World ', ' [Nora] Jakarta PROGRESSION ', ' [Ivy] Sentimental Journey ', ' [Ivy] AssaultMare ', ' [Ivy] Lunar Mare ', ' [Ivy] 99 Glooms ', ' [Ivy] Occidens ', ' [Ivy] New Challenger Approaching ', ' [Ivy] VIS::CRACKED ', ' [Ivy] Wicked Ceremony ', ' [Crystal PuNK] Darling Staring... ', ' [ConneR] Xiorc ', ' [ConneR] REBELLIUM ', ' [ConneR] L`Ultima Cena ', ' [Joe] Take me to the Future ', ' [NEKO#ΦωΦ] Liberation ', ' [NEKO#ΦωΦ] Ramen is God ', ' [NEKO#ΦωΦ] Re: VeLΔTiØN ~ 光道ト破壊ノ双白翼~ ', ' [Xenon] Violet ',' [Ivy] Bloody Purity ', ' [Sagar] Amenemhat ', ' [Sagar] Doldrums ', ' [Sagar] Nídhögg ', ' [Sagar] Sacrifice ', ' [Sagar] Return of the Lamp ', ' [Rin] 「妖怪録、我し来にけり。」 ', ' [Rin] すゝめ☆クノイチの巻 ', ' [Rin] 彩 ', ' [ROBO_Head] Dasein (GLITCH) ', ' [Xenon] Phantom Razor (GLITCH) ', ' [Neko] R.I.P. ', ' [NEKO#ΦωΦ] Happiness Breeze (GLITCH) ', ' [Ivy] Time to Fight ', ' [NEKO#ΦωΦ] 警け！ ', ' [Vanessa]  ͟͞͝ ||̛  ', ' [NEKO#ΦωΦ] Oshama Scramble! ', ' [NEKO#ΦωΦ] BlythE ', ' [NEKO#ΦωΦ] We`re All Gonna Die ', ' [NEKO#ΦωΦ] End of the Moonlight ', ' [Ivy] Sovereign ', ' [Joe] Hydrangea (GLITCH) ', ' [Ivy] paradigm-paragramme-program ', ' [Ivy] Halcyon '  ]

xiii = [ ' [PAFF] Lilac for Anabel ', ' [NEKO#ΦωΦ] Brain Power ', ' [NEKO#ΦωΦ] Praystation (HiTECH NINJA Remix) ', ' [NEKO#ΦωΦ] Online ', ' [NEKO#ΦωΦ] UnNOT!CED ', ' [NEKO#ΦωΦ] 下水鳴動して鼠一匹 ', ' [NEKO#ΦωΦ] Walnuts Walkers ', ' [Neko] Chocolate Missile ', ' [Neko] Log In ', ' [ROBO_Head] Devillic Sphere ', ' [ROBO_Head] Pure Powerstomper ', ' [ROBO_Head] EMber ', ' [ROBO_Head] Midnight ', ' [ROBO_Head] Dead Point ', ' [ROBO_Head] Jazzy Glitch Machine ', ' [ROBO_Head] dimensionalize nervous breakdown [rev.flat] ', ' [ROBO_Head] NRG_Tech ', ' [ROBO_Head] Dead Master ', ' [ROBO_Head] Accelerator ', ' [ROBO_Head] Armaros ', ' [ROBO_Head] Milky Way Galaxy (SIHanatsuka Remix) ', ' [ROBO_Head] Fade Into The Darkness ', ' [Nora] Bastard of Hardcore ', ' [Ivy] Biotonic ', ' [Ivy] Alexandrite ', ' [Ivy] Tokiwatari ', ' [Ivy] BloodyMare ', ' [Ivy] Red Five ', ' [Ivy] What`s Your PR.Ice? ', ' [Crystal PuNK] Effervesce ', ' [Crystal PuNK] Deep Dive ', ' [Crystal PuNK] Dark Madness ', ' [Crystal PuNK] Crimson Fate ', ' [Crystal PuNK] Familiar Craze ', ' [Xenon] INSPION ', ' [Xenon] Whispers in my Head ', ' [Xenon] Phantom Razor ', ' [Xenon] Samurai ', ' [Xenon] Chosen ', ' [Xenon] Ultimate feat. 放課後のあいつ ', ' [ConneR] Imprinting ', ' [ConneR] tondari-hanetari ', ' [ConneR] Nostalgia Sonatina ', ' [ConneR] Aphasia ', ' [ConneR] Demetrius ', ' [ConneR] Deus Ex Machina ', ' [Cherry] LEVEL4 ', ' [Cherry] SYSTEMFEIT ', ' [Joe] Turnstile Jumper ', ' [Joe] Open the Game ', ' [Joe] Higher and Higher ', ' [Joe] Bass Music ', ' [Miku] BREAK IT ', ' [Miku] 魔法みたいなミュージック！ ', ' [NEKO#ΦωΦ] Rebirth ',' [Sagar] Immram Brain ', ' [Sagar] Space Alien ', ' [Sagar] Legacy ', ' [Sagar] A Portent of the Silver Wheel ', ' [Rin] The Siege ', ' [Rin] 三灯火 ', ' [Rin] 決戦 ', ' [PAFF] Gravity (GLITCH) ', ' [ROBO_Head] Deadly Slot Game (GLITCH) ', ' [Ivy] DigiGroove ', ' [Ivy] Leaving All Behind ', ' [Ivy] Libera me ', ' [Ivy] Qualia ', ' [Cherry] CREDENCE (GLITCH) ', ' [Nora] Grand Emotion ', ' [NEKO#ΦωΦ] 気楽なCloudy ', ' [Vanessa] RA ', ' [Vanessa] V. //System Offline// ', ' [NEKO#ΦωΦ] DON`T STOP ROCKIN` ', ' [NEKO#ΦωΦ] 超常マイマイン ', ' [NEKO#ΦωΦ] glory day ', ' [PAFF] Re:Boost (GLITCH)', ' [Kizuna AI] Hello, Morning (Prod. Nor) ', ' [Kizuna AI] over the reality (Prod. Avec Avec) ', ' [Kizuna AI] melty world (Prod. TeddyLoid) ', ' [Aroma] Perspectives (GLITCH) ', ' [Bo Bo] Snow Blossom ', ' [Bo Bo] Quinsialyn ', ' [Bo Bo] 神様と羊飼い ', ' [NEKO#ΦωΦ] Stewrica -Cross- ', ' [Bo Bo] NORDLYS ', ' [Alice] 都市の呼吸 '  ]

xii = [ ' [PAFF] Body Talk ', ' [PAFF] Baptism of Fire (CliqTrack remix) ', ' [PAFF] Gravity ', ' [PAFF] Cityscape ', ' [PAFF] Light up my love!! ', ' [NEKO#ΦωΦ] The Spark ', ' [NEKO#ΦωΦ] Resurrection 💚 ', ' [NEKO#ΦωΦ] Happiness Breeze ', ' [NEKO#ΦωΦ] Alterna Pt.1 -Cosmogony- ', ' [NEKO#ΦωΦ] Zealous Hearts (Rayark Edit) ', ' [NEKO#ΦωΦ] Stranger ', ' [NEKO#ΦωΦ] TOKONOMA Spacewalk ', ' [ROBO_Head] Deadly Slot Game ', ' [ROBO_Head] Make Me Burn ', ' [ROBO_Head] Claim the Game ', ' [ROBO_Head] Dasein ', ' [ROBO_Head] cold ', ' [ROBO_Head] ViRUS ', ' [ROBO_Head] Hagiasmos ', ' [ROBO_Head] SHIRO ', ' [Ivy] Reset ', ' [Ivy] Purge ', ' [Ivy] Area184 ', ' [Ivy] Pressure ', ' [Ivy] Cristalisia ', ' [Crystal PuNK] Chandelier XIII ', ' [Crystal PuNK] Sunshine Duration ', ' [Crystal PuNK] βinαrΨ ', ' [Crystal PuNK] Malstream ', ' [Crystal PuNK] V.R.W (feat. shully) ', ' [Miku] Can`t Make a Song!! ', ' [Miku] Ten Thousand Stars ', ' [Miku] Cybernetic ', ' [Xenon] concentric circles ', ' [Xenon] To The Light ', ' [ConneR] Gekkouka ', ' [ConneR] Light of Buenos Aires ', ' [ConneR] Instinct ', ' [ConneR] Olympia ', ' [Cherry] Living for you (Andy Tunstall remix) ', ' [Cherry] RETRIEVE ', ' [Cherry] CREDENCE ', ' [Cherry] hunted ', ' [Cherry] Realize ', ' [Joe] Childish ', ' [Joe] Standby for Action ', ' [Joe] Hydrangea ', ' [Aroma] Spotlight On ', ' [Nora] Uranus ', ' [Nora] Phagy Mutation ', ' [Neko] I can avoid it.#φωφ ', ' [Neko] リラ ', ' [NEKO#ΦωΦ] Hydra ', ' [Xenon] Asylum ',' [Ivy] Saika ', ' [Ivy] To Further Dream ', ' [Sagar] Elysium ', ' [Rin] The Grand Debate ', ' [PAFF] KANATA (GLITCH) ', ' [Vanessa] II-V ', ' [Vanessa] duality ', ' [Vanessa] CHAOS //System Offline// ', ' [Vanessa] The whole rest ', ' [Kizuna AI] AIAIAI (feat. 中田ヤスタカ) ', ' [Kizuna AI] future base (Prod. Yunomi) ', ' [Kizuna AI] meet you (Prod. DÉ DÉ MOUSE) ', ' [NEKO#ΦωΦ] Play the Future ', ' [NEKO#ΦωΦ] Ask to Wind Live Mix ', ' [NEKO#ΦωΦ] Hello Pinky ', ' [NEKO#ΦωΦ] U.A.D ', ' [NEKO#ΦωΦ] LOUDER MACHINE ', ' [Bo Bo] Äventyr ', ' [Bo Bo] 黎明-REIMEI- ', ' [Alice] Friction ', ' [Alice] I hate to tell you ', ' [Alice] To next page '  ]

xi = [ ' [PAFF] Bullet Waiting for Me (James Landino remix) ', ' [PAFF] Re:Boost ', ' [PAFF] Green Hope ', ' [PAFF] Blossoms for Life ', ' [PAFF] So In Love ', ' [PAFF] Favorites ', ' [PAFF] Make Me Alive ', ' [PAFF] I Wish You Were Mine ', ' [Aroma] No One Can`t Stop Me ', ' [Aroma] Make U Mine ', ' [NEKO#ΦωΦ] extinguisher ', ' [NEKO#ΦωΦ] Hesitant Blade ', ' [Neko] 一啖兩啖 ', ' [ROBO_Head] Restriction ', ' [ROBO_Head] Luolimasi ', ' [ROBO_Head] Grimoire of Crimson ', ' [ROBO_Head] Nocturnal Type ', ' [Nora] Dance till Dawn ', ' [Nora] Starlight (KIVΛ Remix) ', ' [Nora] Eternity ', ' [Nora] ATONEMENT ', ' [Ivy] D R G ', ' [Xenon] Return ', ' [Xenon] Fighting ', ' [Xenon] IOLITE-SUNSTONE ', ' [Xenon] Karma ', ' [ConneR] Abduction ', ' [ConneR] I luv U ', ' [Cherry] I`M NOT ', ' [Cherry] Stop at nothing (Andy Tunstall remix) ', ' [Cherry] Still ', ' [Cherry] Capture me ', ' [JOE] Juicy Gossip ', ' [JOE] Absolutely ', ' [JOE] Nautilus ', ' [Miku] Blue Star ', ' [Miku] ラッキー☆オーブ ', ' [Miku] Glass Wall ', ' [Miku] ラッキー☆オーブ(3R2 Remix) ',' [NEKO#ΦωΦ] Rei ', ' [Ivy] Masquerade ', ' [Ivy] Quantum Labyrinth ', ' [Crystal PuNK] The Cross (feat. Silvia Su) ', ' [Rin] Mari-Temari ', ' [Rin] Inari ', ' [Ivy] Heat Ring ', ' [Aroma] Beautiful Lie ', ' [PAFF] Sleeping Beast ', ' [Vanessa] syūten ', ' [Vanessa] Rosa Rubus ', ' [Kizuna AI] new world (Prod. Yunomi)', ' [Kizuna AI] miracle step (Prod. Nor) ', ' [NEKO#ΦωΦ] OblivioN ', ' [Bo Bo] End of fireworks ', ' [Ivy] Secret Garden ', ' [Alice] Utopiosphere '  ]

x = [ ' [PAFF] Survive ', ' [PAFF] Fight Another Day (Andy Tunstall remix) ', ' [PAFF] Fireflies (Funk Fiction remix) ', ' [PAFF] New World ', ' [PAFF] Who Am I? ', ' [PAFF] PIXIE DUST ', ' [Aroma] Anzen Na Kusuri ', ' [Aroma] Perspectives ', ' [Aroma] Neon Escape ', ' [NEKO#ΦωΦ] Hard Landing ', ' [NEKO#ΦωΦ] Sdorica The Story Unfolds ', ' [Neko] Pink Graduation ', ' [ROBO_Head] Awakening ', ' [Ivy] Homebound Train & Moving Thoughts ', ' [Xenon] Black Hole ', ' [Xenon] Sairai ', ' [Miku] Miku ', ' [Miku] Sharing The World ',' [Rin] Starry Summoner ', ' [Vanessa] Anchor ', ' [Ivy] Summer Zephyr ', ' [NEKO#ΦωΦ] Pounding Destination ', ' [PAFF] Inspiration ', ' [PAFF] No-Effected World ', ' [Alice] Living In The One ', ' [Alice] The Beautiful Moonlight '  ]

ix = [ ' [PAFF] KANATA ', ' [PAFF] Under the same sky ', ' [PAFF] Winter Games ', ' [PAFF] More Than Diamond ', ' [PAFF] Recall ', ' [Aroma] change ', ' [Aroma] 風の声 ', ' [NEKO#ΦωΦ] One Way Love ', ' [NEKO#ΦωΦ] Sunday Night Blues ', ' [Cherry] Scenery in your eyes ', ' [Miku] Decade ', ' [Vanessa] Used to be ', ' [Kizuna AI] mirai (Prod. ☆Taku Takahashi) ', ' [Kizuna AI] hello, alone (Prod. MATZ) ', ' [Alice] Legacy ', ' [Alice] YUBIKIRI-GENMAN ' ]

viii = [ ' [Aroma] Bring the light ', ' [Miku] Venus di Ujung Jari ', ' [Miku] 月西江 ' ]
